version: "3.9"
services:
  my-app:
    image: golang:1.23
    container_name: my-app
    hostname: my-app
    tty: true
    working_dir: /src/app/snippetbox
    develop:
      watch:
        - action: sync
          path: ./snippetbox
          target: /src/app/snippetbox
    volumes:
      - $PWD:/src/app
    expose:
      - 4000
