version: "3.9"
services:
  my-app:
    build:
      context: .
      dockerfile: Dockerfile
    command: go run main.go
    container_name: my-app
    hostname: my-app
    tty: true
    working_dir: /app/snippetbox
    ports:
      - "4000:4000"
    develop:
      watch:
        - action: sync+restart
          path: ./snippetbox
          target: /app/snippetbox
