version: "3.8"

services:
  my-app:
    image: golang:1.22
    container_name: my-app
    hostname: my-app
    tty: true
    working_dir: /src/app/snippetbox
    develop:
      watch:
        - action: sync
          path: ./snippetbox
          target: /src/app/snippetbox
    volumes:
      - $PWD:/src/app
    depends_on:
      - my-db
    networks:
      - my-vnet
    expose:
      - 4000

  my-db:
    image: mysql:8.2.0
    container_name: my-db
    hostname: my-db
    restart: always
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'mysqladmin ping -h 127.0.0.1 --password="$$(cat /run/secrets/db-password)" --silent',
        ]
      interval: 3s
      retries: 5
      start_period: 30s
    secrets:
      - db-password
    networks:
      - my-vnet
    expose:
      - 3306
    volumes:
      - ./data/db:/var/lib/mysql
      #- ./.initialize_db:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=snippetbox
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password

secrets:
  db-password:
    file: .secrets/db-password.txt
